/**
 * CARNES — ~38 ingredientes
 * Macros por 100 g en crudo, salvo indicación.
 * Fuente: USDA FoodData Central 2024-2025.
 */
import { IngredientSeedData } from "../types";

export const carnes: IngredientSeedData[] = [
  // ── POLLO ──────────────────────────────────────────────────────────────
  {
    name: "Pechuga de pollo",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 120,
        protein: 22.5,
        carbs: 0,
        fat: 2.6,
        fiber: 0,
        weightFactor: 1.0,
      },
      {
        name: "Cocinada",
        isDefault: false,
        calories: 165,
        protein: 31.0,
        carbs: 0,
        fat: 3.6,
        fiber: 0,
        weightFactor: 0.75,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "unidad", gramsPerUnit: 200 },
    ],
  },
  {
    name: "Muslo de pollo",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 177,
        protein: 18.4,
        carbs: 0,
        fat: 11.3,
        fiber: 0,
      },
      {
        name: "Cocinado",
        isDefault: false,
        calories: 209,
        protein: 26.2,
        carbs: 0,
        fat: 10.9,
        fiber: 0,
        weightFactor: 0.78,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "unidad", gramsPerUnit: 150 },
    ],
  },
  {
    name: "Contramuslo de pollo",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 185,
        protein: 17.0,
        carbs: 0,
        fat: 12.5,
        fiber: 0,
      },
      {
        name: "Cocinado",
        isDefault: false,
        calories: 210,
        protein: 24.2,
        carbs: 0,
        fat: 11.8,
        fiber: 0,
        weightFactor: 0.78,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "unidad", gramsPerUnit: 130 },
    ],
  },
  {
    name: "Pollo entero",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 215,
        protein: 18.6,
        carbs: 0,
        fat: 15.1,
        fiber: 0,
      },
      {
        name: "Asado",
        isDefault: false,
        calories: 239,
        protein: 27.3,
        carbs: 0,
        fat: 13.6,
        fiber: 0,
        weightFactor: 0.72,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Alita de pollo",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 203,
        protein: 18.3,
        carbs: 0,
        fat: 13.7,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "unidad", gramsPerUnit: 50 },
    ],
  },
  // ── PAVO ───────────────────────────────────────────────────────────────
  {
    name: "Pechuga de pavo",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 135,
        protein: 29.9,
        carbs: 0,
        fat: 1.0,
        fiber: 0,
      },
      {
        name: "Cocinada",
        isDefault: false,
        calories: 189,
        protein: 28.5,
        carbs: 0.1,
        fat: 7.4,
        fiber: 0,
        weightFactor: 0.75,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "unidad", gramsPerUnit: 250 },
    ],
  },
  // ── TERNERA / BUEY ─────────────────────────────────────────────────────
  {
    name: "Carne picada de ternera",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 250,
        protein: 17.2,
        carbs: 0,
        fat: 20.0,
        fiber: 0,
      },
      {
        name: "Cocinada",
        isDefault: false,
        calories: 272,
        protein: 26.1,
        carbs: 0,
        fat: 17.6,
        fiber: 0,
        weightFactor: 0.75,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Solomillo de ternera",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 178,
        protein: 26.3,
        carbs: 0,
        fat: 7.5,
        fiber: 0,
      },
      {
        name: "Cocinado",
        isDefault: false,
        calories: 212,
        protein: 32.1,
        carbs: 0,
        fat: 8.9,
        fiber: 0,
        weightFactor: 0.72,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Entrecot",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 219,
        protein: 23.5,
        carbs: 0,
        fat: 13.3,
        fiber: 0,
      },
      {
        name: "A la plancha",
        isDefault: false,
        calories: 250,
        protein: 30.4,
        carbs: 0,
        fat: 13.5,
        fiber: 0,
        weightFactor: 0.72,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Lomo de ternera",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 200,
        protein: 22.0,
        carbs: 0,
        fat: 12.0,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Hígado de ternera",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 135,
        protein: 20.4,
        carbs: 3.9,
        fat: 3.6,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  // ── CERDO ──────────────────────────────────────────────────────────────
  {
    name: "Lomo de cerdo",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 242,
        protein: 21.0,
        carbs: 0,
        fat: 16.8,
        fiber: 0,
      },
      {
        name: "Asado",
        isDefault: false,
        calories: 270,
        protein: 26.5,
        carbs: 0,
        fat: 17.1,
        fiber: 0,
        weightFactor: 0.72,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Solomillo de cerdo",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 143,
        protein: 21.2,
        carbs: 0,
        fat: 5.9,
        fiber: 0,
      },
      {
        name: "Cocinado",
        isDefault: false,
        calories: 184,
        protein: 28.9,
        carbs: 0,
        fat: 6.9,
        fiber: 0,
        weightFactor: 0.72,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Costillas de cerdo",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 278,
        protein: 19.0,
        carbs: 0,
        fat: 22.0,
        fiber: 0,
      },
      {
        name: "Asadas",
        isDefault: false,
        calories: 309,
        protein: 24.2,
        carbs: 0,
        fat: 23.2,
        fiber: 0,
        weightFactor: 0.72,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Carrilleras de cerdo",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 160,
        protein: 18.0,
        carbs: 0,
        fat: 9.0,
        fiber: 0,
      },
      {
        name: "Estofadas",
        isDefault: false,
        calories: 185,
        protein: 22.5,
        carbs: 3.0,
        fat: 8.5,
        fiber: 0,
        weightFactor: 0.78,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "unidad", gramsPerUnit: 180 },
    ],
  },
  {
    name: "Panceta",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 417,
        protein: 12.0,
        carbs: 0,
        fat: 40.3,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Carne picada mixta",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 240,
        protein: 18.0,
        carbs: 0,
        fat: 18.5,
        fiber: 0,
      },
      {
        name: "Cocinada",
        isDefault: false,
        calories: 265,
        protein: 25.0,
        carbs: 0,
        fat: 18.0,
        fiber: 0,
        weightFactor: 0.75,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  // ── EMBUTIDOS ──────────────────────────────────────────────────────────
  {
    name: "Jamón serrano",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Curado",
        isDefault: true,
        calories: 203,
        protein: 30.5,
        carbs: 1.0,
        fat: 7.0,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "loncha", gramsPerUnit: 20 },
    ],
  },
  {
    name: "Jamón cocido",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Cocido",
        isDefault: true,
        calories: 107,
        protein: 15.0,
        carbs: 1.0,
        fat: 4.5,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "loncha", gramsPerUnit: 20 },
    ],
  },
  {
    name: "Chorizo",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Curado",
        isDefault: true,
        calories: 370,
        protein: 17.0,
        carbs: 2.0,
        fat: 33.0,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "unidad", gramsPerUnit: 55 },
      { unitName: "loncha", gramsPerUnit: 15 },
    ],
  },
  {
    name: "Salchichón",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Curado",
        isDefault: true,
        calories: 380,
        protein: 20.0,
        carbs: 1.5,
        fat: 32.0,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "loncha", gramsPerUnit: 15 },
    ],
  },
  {
    name: "Fuet",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Curado",
        isDefault: true,
        calories: 390,
        protein: 20.5,
        carbs: 1.8,
        fat: 33.5,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Mortadela",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Cocida",
        isDefault: true,
        calories: 311,
        protein: 14.0,
        carbs: 2.5,
        fat: 27.0,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "loncha", gramsPerUnit: 25 },
    ],
  },
  {
    name: "Salami",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Curado",
        isDefault: true,
        calories: 336,
        protein: 21.0,
        carbs: 1.5,
        fat: 27.3,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "loncha", gramsPerUnit: 8 },
    ],
  },
  {
    name: "Salchicha fresca",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 301,
        protein: 12.0,
        carbs: 3.7,
        fat: 25.8,
        fiber: 0,
      },
      {
        name: "Cocinada",
        isDefault: false,
        calories: 326,
        protein: 14.5,
        carbs: 4.0,
        fat: 28.0,
        fiber: 0,
        weightFactor: 0.8,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "unidad", gramsPerUnit: 60 },
    ],
  },
  {
    name: "Butifarra",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 310,
        protein: 15.0,
        carbs: 3.0,
        fat: 27.0,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "unidad", gramsPerUnit: 100 },
    ],
  },
  {
    name: "Morcilla",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 327,
        protein: 13.7,
        carbs: 14.5,
        fat: 24.6,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "unidad", gramsPerUnit: 120 },
    ],
  },
  {
    name: "Sobrasada",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Curada",
        isDefault: true,
        calories: 434,
        protein: 14.0,
        carbs: 2.0,
        fat: 40.0,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  // ── CORDERO / OTROS ────────────────────────────────────────────────────
  {
    name: "Cordero",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 294,
        protein: 24.5,
        carbs: 0,
        fat: 20.9,
        fiber: 0,
      },
      {
        name: "Asado",
        isDefault: false,
        calories: 332,
        protein: 28.8,
        carbs: 0,
        fat: 23.2,
        fiber: 0,
        weightFactor: 0.72,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Conejo",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 136,
        protein: 20.1,
        carbs: 0,
        fat: 5.5,
        fiber: 0,
      },
      {
        name: "Estofado",
        isDefault: false,
        calories: 165,
        protein: 25.8,
        carbs: 0,
        fat: 6.2,
        fiber: 0,
        weightFactor: 0.72,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Pato",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 337,
        protein: 19.0,
        carbs: 0,
        fat: 28.4,
        fiber: 0,
      },
      {
        name: "Asado",
        isDefault: false,
        calories: 250,
        protein: 29.2,
        carbs: 0,
        fat: 14.2,
        fiber: 0,
        weightFactor: 0.65,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Codorniz",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 192,
        protein: 21.8,
        carbs: 0,
        fat: 11.4,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "unidad", gramsPerUnit: 100 },
    ],
  },
  {
    name: "Hígado de pollo",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 119,
        protein: 16.9,
        carbs: 0.7,
        fat: 4.8,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Bacon",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 541,
        protein: 12.6,
        carbs: 1.4,
        fat: 52.3,
        fiber: 0,
      },
      {
        name: "Frito",
        isDefault: false,
        calories: 541,
        protein: 35.0,
        carbs: 1.4,
        fat: 42.0,
        fiber: 0,
        weightFactor: 0.55,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "loncha", gramsPerUnit: 20 },
    ],
  },
  {
    name: "Pato confitado",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Confitado",
        isDefault: true,
        calories: 290,
        protein: 22.0,
        carbs: 0,
        fat: 22.0,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  // ── AÑADIDOS DESDE SQL ────────────────────────────────────────────────────
  {
    name: "Filetes de ternera",
    unit: "g",
    variants: [
      {
        name: "Crudos",
        isDefault: true,
        calories: 150,
        protein: 22,
        carbs: 0,
        fat: 7,
        fiber: 0,
      },
      {
        name: "A la plancha",
        isDefault: false,
        calories: 175,
        protein: 30,
        carbs: 0,
        fat: 6,
        fiber: 0,
        weightFactor: 0.72,
      },
      {
        name: "Empanados",
        isDefault: false,
        calories: 285,
        protein: 20,
        carbs: 17,
        fat: 15,
        fiber: 1,
        weightFactor: 0.78,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "filete", gramsPerUnit: 120 },
    ],
  },
  {
    name: "Redondo de ternera",
    unit: "g",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 125,
        protein: 21,
        carbs: 0,
        fat: 4,
        fiber: 0,
      },
      {
        name: "Asado",
        isDefault: false,
        calories: 165,
        protein: 29,
        carbs: 0,
        fat: 5,
        fiber: 0,
        weightFactor: 0.68,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Rabo de ternera",
    unit: "g",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 280,
        protein: 17,
        carbs: 0,
        fat: 24,
        fiber: 0,
      },
      {
        name: "Estofado",
        isDefault: false,
        calories: 240,
        protein: 24,
        carbs: 2,
        fat: 15,
        fiber: 0,
        weightFactor: 0.7,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Chuletas de cerdo",
    unit: "g",
    variants: [
      {
        name: "Crudas",
        isDefault: true,
        calories: 215,
        protein: 17,
        carbs: 0,
        fat: 16,
        fiber: 0,
      },
      {
        name: "A la plancha",
        isDefault: false,
        calories: 245,
        protein: 24,
        carbs: 0,
        fat: 16,
        fiber: 0,
        weightFactor: 0.72,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "chuleta", gramsPerUnit: 135 },
    ],
  },
  {
    name: "Secreto ibérico",
    unit: "g",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 335,
        protein: 16,
        carbs: 0,
        fat: 30,
        fiber: 0,
      },
      {
        name: "A la plancha",
        isDefault: false,
        calories: 360,
        protein: 22,
        carbs: 0,
        fat: 30,
        fiber: 0,
        weightFactor: 0.72,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Pluma ibérica",
    unit: "g",
    variants: [
      {
        name: "Cruda",
        isDefault: true,
        calories: 260,
        protein: 18,
        carbs: 0,
        fat: 21,
        fiber: 0,
      },
      {
        name: "A la plancha",
        isDefault: false,
        calories: 280,
        protein: 25,
        carbs: 0,
        fat: 20,
        fiber: 0,
        weightFactor: 0.72,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Presa ibérica",
    unit: "g",
    variants: [
      {
        name: "Cruda",
        isDefault: true,
        calories: 290,
        protein: 17,
        carbs: 0,
        fat: 25,
        fiber: 0,
      },
      {
        name: "A la plancha",
        isDefault: false,
        calories: 310,
        protein: 24,
        carbs: 0,
        fat: 24,
        fiber: 0,
        weightFactor: 0.72,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Papada de cerdo",
    unit: "g",
    variants: [
      {
        name: "Cruda",
        isDefault: true,
        calories: 480,
        protein: 10,
        carbs: 0,
        fat: 48,
        fiber: 0,
      },
      {
        name: "Curada/guanciale",
        isDefault: false,
        calories: 520,
        protein: 11,
        carbs: 0,
        fat: 54,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Solomillo de pavo",
    unit: "g",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 110,
        protein: 23,
        carbs: 0,
        fat: 1.5,
        fiber: 0,
      },
      {
        name: "A la plancha",
        isDefault: false,
        calories: 140,
        protein: 30,
        carbs: 0,
        fat: 2,
        fiber: 0,
        weightFactor: 0.72,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Jamoncitos de pollo",
    unit: "g",
    variants: [
      {
        name: "Crudos",
        isDefault: true,
        calories: 158,
        protein: 18,
        carbs: 0,
        fat: 9.5,
        fiber: 0,
      },
      {
        name: "Al horno",
        isDefault: false,
        calories: 185,
        protein: 25,
        carbs: 0,
        fat: 9,
        fiber: 0,
        weightFactor: 0.75,
      },
    ],
    conversions: [{ unitName: "jamoncito", gramsPerUnit: 80 }],
  },
  {
    name: "Codillo de cerdo",
    unit: "g",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 290,
        protein: 16,
        carbs: 0,
        fat: 25,
        fiber: 0,
      },
      {
        name: "Cocido",
        isDefault: false,
        calories: 265,
        protein: 22,
        carbs: 0,
        fat: 20,
        fiber: 0,
        weightFactor: 0.72,
      },
    ],
    conversions: [{ unitName: "codillo", gramsPerUnit: 600 }],
  },
  {
    name: "Carne picada mixta",
    unit: "g",
    variants: [
      {
        name: "Cruda",
        isDefault: true,
        calories: 210,
        protein: 17,
        carbs: 0,
        fat: 16,
        fiber: 0,
      },
      {
        name: "Cocinada",
        isDefault: false,
        calories: 240,
        protein: 23,
        carbs: 0,
        fat: 16,
        fiber: 0,
        weightFactor: 0.72,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "ración (100g)", gramsPerUnit: 100 },
    ],
  },
  {
    name: "Hamburguesa de ternera",
    unit: "g",
    variants: [
      {
        name: "Cruda",
        isDefault: true,
        calories: 250,
        protein: 17,
        carbs: 2,
        fat: 19,
        fiber: 0,
      },
      {
        name: "A la plancha",
        isDefault: false,
        calories: 270,
        protein: 24,
        carbs: 2,
        fat: 18,
        fiber: 0,
        weightFactor: 0.8,
      },
    ],
    conversions: [
      { unitName: "hamburguesa (100g)", gramsPerUnit: 100 },
      { unitName: "hamburguesa grande (150g)", gramsPerUnit: 150 },
    ],
  },
  {
    name: "Chuletas de cordero",
    unit: "g",
    variants: [
      {
        name: "Crudas",
        isDefault: true,
        calories: 250,
        protein: 15,
        carbs: 0,
        fat: 21,
        fiber: 0,
      },
      {
        name: "A la plancha",
        isDefault: false,
        calories: 265,
        protein: 20,
        carbs: 0,
        fat: 21,
        fiber: 0,
        weightFactor: 0.68,
      },
      {
        name: "Al horno",
        isDefault: false,
        calories: 260,
        protein: 21,
        carbs: 0,
        fat: 19,
        fiber: 0,
        weightFactor: 0.7,
      },
    ],
    conversions: [
      { unitName: "chuleta", gramsPerUnit: 80 },
      { unitName: "kg", gramsPerUnit: 1000 },
    ],
  },
  {
    name: "Pierna de cordero",
    unit: "g",
    variants: [
      {
        name: "Cruda",
        isDefault: true,
        calories: 195,
        protein: 16,
        carbs: 0,
        fat: 14,
        fiber: 0,
      },
      {
        name: "Asada",
        isDefault: false,
        calories: 235,
        protein: 25,
        carbs: 0,
        fat: 15,
        fiber: 0,
        weightFactor: 0.65,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Paletilla de cordero",
    unit: "g",
    variants: [
      {
        name: "Cruda",
        isDefault: true,
        calories: 230,
        protein: 15,
        carbs: 0,
        fat: 19,
        fiber: 0,
      },
      {
        name: "Asada",
        isDefault: false,
        calories: 255,
        protein: 22,
        carbs: 0,
        fat: 18,
        fiber: 0,
        weightFactor: 0.65,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Carrilleras de ternera",
    unit: "g",
    variants: [
      {
        name: "Crudas",
        isDefault: true,
        calories: 155,
        protein: 19,
        carbs: 0,
        fat: 8,
        fiber: 0,
      },
      {
        name: "Estofadas",
        isDefault: false,
        calories: 190,
        protein: 28,
        carbs: 3,
        fat: 8,
        fiber: 0,
        weightFactor: 0.72,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "carrillera", gramsPerUnit: 200 },
    ],
  },
  {
    name: "Riñones de cerdo",
    unit: "g",
    variants: [
      {
        name: "Crudos",
        isDefault: true,
        calories: 100,
        protein: 16,
        carbs: 1,
        fat: 3.5,
        fiber: 0,
      },
      {
        name: "A la plancha",
        isDefault: false,
        calories: 115,
        protein: 22,
        carbs: 1,
        fat: 3.5,
        fiber: 0,
        weightFactor: 0.75,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
];
