/**
 * PESCADOS Y MARISCOS — ~35 ingredientes
 * Macros por 100 g en crudo, salvo indicación.
 * Fuente: USDA FoodData Central 2024-2025.
 */
import { IngredientSeedData } from "../types";

export const pescadosMariscos: IngredientSeedData[] = [
  // ── PESCADOS AZULES ────────────────────────────────────────────────────
  {
    name: "Salmón",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 208,
        protein: 20.4,
        carbs: 0,
        fat: 13.4,
        fiber: 0,
      },
      {
        name: "Cocinado",
        isDefault: false,
        calories: 206,
        protein: 27.3,
        carbs: 0,
        fat: 9.7,
        fiber: 0,
        weightFactor: 0.78,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "filete", gramsPerUnit: 150 },
    ],
  },
  {
    name: "Atún fresco",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 144,
        protein: 23.4,
        carbs: 0,
        fat: 4.9,
        fiber: 0,
      },
      {
        name: "Cocinado",
        isDefault: false,
        calories: 184,
        protein: 29.9,
        carbs: 0,
        fat: 6.3,
        fiber: 0,
        weightFactor: 0.78,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "filete", gramsPerUnit: 180 },
    ],
  },
  {
    name: "Atún en lata",
    unit: "g",
    defaultLocation: "despensa",
    preferredUnit: "lata",
    variants: [
      {
        name: "Escurrido en agua",
        isDefault: true,
        calories: 116,
        protein: 25.5,
        carbs: 0,
        fat: 0.8,
        fiber: 0,
      },
      {
        name: "En aceite de oliva",
        isDefault: false,
        calories: 200,
        protein: 24.0,
        carbs: 0,
        fat: 11.5,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "lata", gramsPerUnit: 80 },
    ],
  },
  {
    name: "Sardinas",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 208,
        protein: 24.6,
        carbs: 0,
        fat: 11.5,
        fiber: 0,
      },
      {
        name: "En lata (tomate)",
        isDefault: false,
        calories: 195,
        protein: 18.0,
        carbs: 2.0,
        fat: 12.3,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "unidad", gramsPerUnit: 30 },
      { unitName: "lata", gramsPerUnit: 90 },
    ],
  },
  {
    name: "Anchoas",
    unit: "g",
    defaultLocation: "nevera",
    preferredUnit: "filete",
    variants: [
      {
        name: "En aceite",
        isDefault: true,
        calories: 210,
        protein: 28.9,
        carbs: 0,
        fat: 9.7,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "filete", gramsPerUnit: 4 },
    ],
  },
  {
    name: "Boquerones",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 131,
        protein: 20.1,
        carbs: 0,
        fat: 4.8,
        fiber: 0,
      },
      {
        name: "En vinagre",
        isDefault: false,
        calories: 100,
        protein: 17.0,
        carbs: 1.0,
        fat: 3.0,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Caballa",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 205,
        protein: 18.6,
        carbs: 0,
        fat: 13.9,
        fiber: 0,
      },
      {
        name: "Cocinada",
        isDefault: false,
        calories: 262,
        protein: 23.9,
        carbs: 0,
        fat: 17.8,
        fiber: 0,
        weightFactor: 0.78,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "filete", gramsPerUnit: 120 },
    ],
  },
  {
    name: "Trucha",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 141,
        protein: 19.9,
        carbs: 0,
        fat: 6.2,
        fiber: 0,
      },
      {
        name: "Cocinada",
        isDefault: false,
        calories: 190,
        protein: 26.6,
        carbs: 0,
        fat: 8.5,
        fiber: 0,
        weightFactor: 0.78,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "filete", gramsPerUnit: 150 },
    ],
  },
  // ── PESCADOS BLANCOS ───────────────────────────────────────────────────
  {
    name: "Bacalao",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Fresco crudo",
        isDefault: true,
        calories: 82,
        protein: 17.8,
        carbs: 0,
        fat: 0.7,
        fiber: 0,
      },
      {
        name: "Seco salado",
        isDefault: false,
        calories: 290,
        protein: 62.8,
        carbs: 0,
        fat: 2.4,
        fiber: 0,
      },
      {
        name: "Cocinado",
        isDefault: false,
        calories: 105,
        protein: 22.8,
        carbs: 0,
        fat: 0.9,
        fiber: 0,
        weightFactor: 0.78,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "filete", gramsPerUnit: 150 },
    ],
  },
  {
    name: "Merluza",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 80,
        protein: 17.8,
        carbs: 0,
        fat: 1.3,
        fiber: 0,
      },
      {
        name: "Cocinada",
        isDefault: false,
        calories: 95,
        protein: 20.9,
        carbs: 0,
        fat: 1.6,
        fiber: 0,
        weightFactor: 0.78,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "filete", gramsPerUnit: 160 },
      { unitName: "rodaja", gramsPerUnit: 130 },
    ],
  },
  {
    name: "Lubina",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 97,
        protein: 18.4,
        carbs: 0,
        fat: 2.0,
        fiber: 0,
      },
      {
        name: "Al horno",
        isDefault: false,
        calories: 124,
        protein: 23.6,
        carbs: 0,
        fat: 2.6,
        fiber: 0,
        weightFactor: 0.78,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "unidad", gramsPerUnit: 450 },
    ],
  },
  {
    name: "Dorada",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 100,
        protein: 18.0,
        carbs: 0,
        fat: 2.9,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "unidad", gramsPerUnit: 450 },
    ],
  },
  {
    name: "Lenguado",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 91,
        protein: 18.8,
        carbs: 0,
        fat: 1.2,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "filete", gramsPerUnit: 100 },
    ],
  },
  {
    name: "Rape",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 73,
        protein: 14.5,
        carbs: 0,
        fat: 1.5,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Gallo",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 91,
        protein: 18.8,
        carbs: 0,
        fat: 1.2,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "filete", gramsPerUnit: 100 },
    ],
  },
  {
    name: "Panga",
    unit: "g",
    defaultLocation: "congelador",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 90,
        protein: 15.7,
        carbs: 0,
        fat: 2.9,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "filete", gramsPerUnit: 130 },
    ],
  },
  {
    name: "Mero",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 92,
        protein: 19.4,
        carbs: 0,
        fat: 1.0,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  // ── MARISCOS ───────────────────────────────────────────────────────────
  {
    name: "Gambas",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 99,
        protein: 23.9,
        carbs: 0,
        fat: 0.3,
        fiber: 0,
      },
      {
        name: "Cocidas",
        isDefault: false,
        calories: 99,
        protein: 23.9,
        carbs: 0,
        fat: 0.3,
        fiber: 0,
        weightFactor: 0.85,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "unidad", gramsPerUnit: 10 },
    ],
  },
  {
    name: "Langostinos",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 106,
        protein: 20.3,
        carbs: 0,
        fat: 2.2,
        fiber: 0,
      },
      {
        name: "Cocidos",
        isDefault: false,
        calories: 112,
        protein: 24.0,
        carbs: 0,
        fat: 1.2,
        fiber: 0,
        weightFactor: 0.85,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "unidad", gramsPerUnit: 25 },
    ],
  },
  {
    name: "Mejillones",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 86,
        protein: 11.9,
        carbs: 3.7,
        fat: 2.2,
        fiber: 0,
      },
      {
        name: "Cocidos",
        isDefault: false,
        calories: 172,
        protein: 23.8,
        carbs: 7.4,
        fat: 4.5,
        fiber: 0,
        weightFactor: 0.5,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "unidad", gramsPerUnit: 12 },
    ],
  },
  {
    name: "Almejas",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 74,
        protein: 12.8,
        carbs: 2.6,
        fat: 1.0,
        fiber: 0,
      },
      {
        name: "Cocidas",
        isDefault: false,
        calories: 148,
        protein: 25.6,
        carbs: 5.1,
        fat: 2.0,
        fiber: 0,
        weightFactor: 0.5,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Berberechos",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 82,
        protein: 12.8,
        carbs: 2.6,
        fat: 1.8,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "lata", gramsPerUnit: 60 },
    ],
  },
  {
    name: "Ostras",
    unit: "g",
    defaultLocation: "nevera",
    preferredUnit: "unidad",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 68,
        protein: 7.05,
        carbs: 3.91,
        fat: 2.47,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "unidad", gramsPerUnit: 30 },
    ],
  },
  {
    name: "Vieiras",
    unit: "g",
    defaultLocation: "nevera",
    preferredUnit: "unidad",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 111,
        protein: 20.5,
        carbs: 5.4,
        fat: 0.84,
        fiber: 0,
      },
      {
        name: "Cocinadas",
        isDefault: false,
        calories: 137,
        protein: 24.9,
        carbs: 6.6,
        fat: 1.6,
        fiber: 0,
        weightFactor: 0.85,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "unidad", gramsPerUnit: 45 },
    ],
  },
  {
    name: "Calamar",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 92,
        protein: 15.6,
        carbs: 3.1,
        fat: 1.4,
        fiber: 0,
      },
      {
        name: "Frito",
        isDefault: false,
        calories: 175,
        protein: 18.2,
        carbs: 8.0,
        fat: 8.0,
        fiber: 0,
        weightFactor: 0.75,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Pulpo",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 82,
        protein: 14.9,
        carbs: 2.2,
        fat: 1.0,
        fiber: 0,
      },
      {
        name: "Cocido",
        isDefault: false,
        calories: 164,
        protein: 29.8,
        carbs: 4.4,
        fat: 2.1,
        fiber: 0,
        weightFactor: 0.5,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Sepia",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 79,
        protein: 16.2,
        carbs: 0.8,
        fat: 0.7,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Nécora",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Cocida",
        isDefault: true,
        calories: 97,
        protein: 19.0,
        carbs: 0,
        fat: 1.8,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "unidad", gramsPerUnit: 120 },
    ],
  },
  {
    name: "Bogavante",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 89,
        protein: 18.8,
        carbs: 1.2,
        fat: 0.9,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Langosta",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 89,
        protein: 18.8,
        carbs: 0.5,
        fat: 0.9,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Cangrejo",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Cocido",
        isDefault: true,
        calories: 97,
        protein: 19.0,
        carbs: 0,
        fat: 1.8,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Salmón ahumado",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Ahumado",
        isDefault: true,
        calories: 117,
        protein: 18.3,
        carbs: 0,
        fat: 4.3,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "loncha", gramsPerUnit: 30 },
    ],
  },
  {
    name: "Navajas",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Cocidas",
        isDefault: true,
        calories: 72,
        protein: 11.4,
        carbs: 2.9,
        fat: 1.6,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "unidad", gramsPerUnit: 30 },
    ],
  },
  {
    name: "Palitos de cangrejo",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Procesado",
        isDefault: true,
        calories: 95,
        protein: 8.0,
        carbs: 9.0,
        fat: 2.9,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "unidad", gramsPerUnit: 15 },
    ],
  },
  // ── AÑADIDOS DESDE SQL ──────────────────────────────────────────────────
  {
    name: "Emperador",
    unit: "g",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 121,
        protein: 20,
        carbs: 0,
        fat: 4.5,
        fiber: 0,
      },
      {
        name: "A la plancha",
        isDefault: false,
        calories: 140,
        protein: 26,
        carbs: 0,
        fat: 4.5,
        fiber: 0,
        weightFactor: 0.78,
      },
      {
        name: "Al horno",
        isDefault: false,
        calories: 135,
        protein: 25,
        carbs: 0,
        fat: 4,
        fiber: 0,
        weightFactor: 0.78,
      },
    ],
    conversions: [
      { unitName: "filete", gramsPerUnit: 150 },
      { unitName: "ración", gramsPerUnit: 180 },
    ],
  },
  {
    name: "Rodaballo",
    unit: "g",
    variants: [
      {
        name: "Crudo",
        isDefault: true,
        calories: 95,
        protein: 19,
        carbs: 0,
        fat: 2,
        fiber: 0,
      },
      {
        name: "Al horno",
        isDefault: false,
        calories: 110,
        protein: 23,
        carbs: 0,
        fat: 2,
        fiber: 0,
        weightFactor: 0.78,
      },
    ],
    conversions: [{ unitName: "filete", gramsPerUnit: 150 }],
  },
  {
    name: "Chirlas",
    unit: "g",
    variants: [
      {
        name: "Crudas",
        isDefault: true,
        calories: 60,
        protein: 11,
        carbs: 2,
        fat: 0.8,
        fiber: 0,
      },
      {
        name: "Al vapor",
        isDefault: false,
        calories: 72,
        protein: 13,
        carbs: 2.5,
        fat: 1,
        fiber: 0,
        weightFactor: 0.55,
      },
    ],
    conversions: [
      { unitName: "kg", gramsPerUnit: 1000 },
      { unitName: "ración (150g)", gramsPerUnit: 150 },
    ],
  },
  {
    name: "Percebes",
    unit: "g",
    variants: [
      {
        name: "Cocidos",
        isDefault: true,
        calories: 67,
        protein: 12,
        carbs: 2,
        fat: 1.2,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "percebe", gramsPerUnit: 8 },
      { unitName: "ración (150g)", gramsPerUnit: 150 },
    ],
  },
  {
    name: "Camarones",
    unit: "g",
    variants: [
      {
        name: "Crudos",
        isDefault: true,
        calories: 99,
        protein: 21,
        carbs: 0,
        fat: 1.7,
        fiber: 0,
      },
      {
        name: "Cocidos",
        isDefault: false,
        calories: 105,
        protein: 22,
        carbs: 0,
        fat: 1.8,
        fiber: 0,
        weightFactor: 0.78,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Cigalas",
    unit: "g",
    variants: [
      {
        name: "Crudas",
        isDefault: true,
        calories: 88,
        protein: 19,
        carbs: 0.5,
        fat: 1.2,
        fiber: 0,
      },
      {
        name: "Cocidas",
        isDefault: false,
        calories: 98,
        protein: 21,
        carbs: 0.5,
        fat: 1.5,
        fiber: 0,
        weightFactor: 0.6,
      },
    ],
    conversions: [{ unitName: "cigala", gramsPerUnit: 80 }],
  },
  {
    name: "Buey de mar",
    unit: "g",
    variants: [
      {
        name: "Cocido",
        isDefault: true,
        calories: 87,
        protein: 18.5,
        carbs: 0,
        fat: 1,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
];
