/**
 * SNACKS, PLATOS PREPARADOS, BEBIDAS CON MARCA, PIZZAS, PANES ESPECIALES,
 * CONSERVAS Y ENCURTIDOS
 * Macros por 100g o 100ml según aplique.
 * Fuente: etiquetas de producto / USDA FoodData Central.
 */
import { IngredientSeedData } from "../types";

export const snacksPreparados: IngredientSeedData[] = [
  // ── PATATAS FRITAS CON MARCA ──────────────────────────────────────────────
  {
    name: "Pringles Original",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Original",
        isDefault: true,
        calories: 519,
        protein: 5,
        carbs: 55,
        fat: 31,
        fiber: 3,
      },
    ],
    conversions: [
      { unitName: "tubo grande (185g)", gramsPerUnit: 185 },
      { unitName: "tubo pequeño (40g)", gramsPerUnit: 40 },
      { unitName: "ración (28g)", gramsPerUnit: 28 },
    ],
  },
  {
    name: "Pringles Crema y Cebolla",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Crema y Cebolla",
        isDefault: true,
        calories: 524,
        protein: 5,
        carbs: 55,
        fat: 32,
        fiber: 4,
      },
    ],
    conversions: [
      { unitName: "tubo grande (185g)", gramsPerUnit: 185 },
      { unitName: "ración (28g)", gramsPerUnit: 28 },
    ],
  },
  {
    name: "Pringles Queso",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Queso",
        isDefault: true,
        calories: 527,
        protein: 5.5,
        carbs: 54,
        fat: 33,
        fiber: 3,
      },
    ],
    conversions: [
      { unitName: "tubo grande (185g)", gramsPerUnit: 185 },
      { unitName: "ración (28g)", gramsPerUnit: 28 },
    ],
  },
  {
    name: "Pringles Paprika",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Paprika",
        isDefault: true,
        calories: 521,
        protein: 5,
        carbs: 55,
        fat: 32,
        fiber: 3,
      },
    ],
    conversions: [
      { unitName: "tubo grande (185g)", gramsPerUnit: 185 },
      { unitName: "ración (28g)", gramsPerUnit: 28 },
    ],
  },
  {
    name: "Pringles BBQ",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "BBQ",
        isDefault: true,
        calories: 519,
        protein: 5,
        carbs: 56,
        fat: 31,
        fiber: 3,
      },
    ],
    conversions: [
      { unitName: "tubo grande (185g)", gramsPerUnit: 185 },
      { unitName: "ración (28g)", gramsPerUnit: 28 },
    ],
  },
  {
    name: "Lays Clásicas",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Clásicas (sal)",
        isDefault: true,
        calories: 536,
        protein: 7,
        carbs: 53,
        fat: 34,
        fiber: 4,
      },
    ],
    conversions: [
      { unitName: "bolsa pequeña (28g)", gramsPerUnit: 28 },
      { unitName: "bolsa mediana (150g)", gramsPerUnit: 150 },
    ],
  },
  {
    name: "Lays Onduladas Jamón",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Onduladas Jamón",
        isDefault: true,
        calories: 539,
        protein: 6.5,
        carbs: 56,
        fat: 33,
        fiber: 4,
      },
    ],
    conversions: [{ unitName: "bolsa mediana (150g)", gramsPerUnit: 150 }],
  },
  {
    name: "Lays Onduladas Queso",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Onduladas Queso",
        isDefault: true,
        calories: 540,
        protein: 6.5,
        carbs: 55,
        fat: 34,
        fiber: 4,
      },
    ],
    conversions: [{ unitName: "bolsa mediana (150g)", gramsPerUnit: 150 }],
  },
  {
    name: "Lays Barbacoa",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Barbacoa",
        isDefault: true,
        calories: 535,
        protein: 6.5,
        carbs: 54,
        fat: 33,
        fiber: 4,
      },
    ],
    conversions: [{ unitName: "bolsa mediana (150g)", gramsPerUnit: 150 }],
  },
  {
    name: "Ruffles Queso",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Ruffles Queso",
        isDefault: true,
        calories: 536,
        protein: 6.5,
        carbs: 55,
        fat: 33,
        fiber: 4,
      },
    ],
    conversions: [{ unitName: "bolsa mediana (150g)", gramsPerUnit: 150 }],
  },
  {
    name: "Ruffles Crema Agria",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Ruffles Crema Agria",
        isDefault: true,
        calories: 537,
        protein: 6.5,
        carbs: 55,
        fat: 33,
        fiber: 4,
      },
    ],
    conversions: [{ unitName: "bolsa mediana (150g)", gramsPerUnit: 150 }],
  },
  {
    name: "Doritos Nacho Cheese",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Nacho Cheese",
        isDefault: true,
        calories: 490,
        protein: 6.5,
        carbs: 60,
        fat: 24,
        fiber: 4,
      },
    ],
    conversions: [
      { unitName: "bolsa grande (180g)", gramsPerUnit: 180 },
      { unitName: "ración (28g)", gramsPerUnit: 28 },
    ],
  },
  {
    name: "Doritos Cool Ranch",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Cool Ranch",
        isDefault: true,
        calories: 487,
        protein: 7,
        carbs: 58,
        fat: 25,
        fiber: 4,
      },
    ],
    conversions: [
      { unitName: "bolsa grande (180g)", gramsPerUnit: 180 },
      { unitName: "ración (28g)", gramsPerUnit: 28 },
    ],
  },
  // ── PALOMITAS ────────────────────────────────────────────────────────────
  {
    name: "Palomitas de sal",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Con sal",
        isDefault: true,
        calories: 385,
        protein: 11,
        carbs: 69,
        fat: 7,
        fiber: 14,
      },
    ],
    conversions: [
      { unitName: "bolsa cine (100g)", gramsPerUnit: 100 },
      { unitName: "ración (40g)", gramsPerUnit: 40 },
    ],
  },
  {
    name: "Palomitas de azúcar / caramelo",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Caramelo clásico",
        isDefault: true,
        calories: 430,
        protein: 7,
        carbs: 74,
        fat: 13,
        fiber: 9,
      },
      {
        name: "Caramelo salado",
        isDefault: false,
        calories: 445,
        protein: 7,
        carbs: 72,
        fat: 16,
        fiber: 9,
      },
    ],
    conversions: [
      { unitName: "bolsa cine (100g)", gramsPerUnit: 100 },
      { unitName: "ración (40g)", gramsPerUnit: 40 },
    ],
  },
  {
    name: "Palomitas de mantequilla",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Con mantequilla",
        isDefault: true,
        calories: 430,
        protein: 9,
        carbs: 63,
        fat: 17,
        fiber: 10,
      },
    ],
    conversions: [{ unitName: "ración (40g)", gramsPerUnit: 40 }],
  },
  {
    name: "Palomitas microondas (sal)",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Con sal (microondas)",
        isDefault: true,
        calories: 395,
        protein: 10,
        carbs: 65,
        fat: 13,
        fiber: 12,
      },
    ],
    conversions: [{ unitName: "bolsa microondas (90g)", gramsPerUnit: 90 }],
  },
  {
    name: "Palomitas microondas (mantequilla)",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Con mantequilla (microondas)",
        isDefault: true,
        calories: 462,
        protein: 7,
        carbs: 57,
        fat: 22,
        fiber: 9,
      },
    ],
    conversions: [{ unitName: "bolsa microondas (90g)", gramsPerUnit: 90 }],
  },
  {
    name: "Palomitas microondas (light)",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Light (microondas)",
        isDefault: true,
        calories: 340,
        protein: 9,
        carbs: 62,
        fat: 7,
        fiber: 11,
      },
    ],
    conversions: [{ unitName: "bolsa microondas (90g)", gramsPerUnit: 90 }],
  },
  // ── OTROS SNACKS ─────────────────────────────────────────────────────────
  {
    name: "Gusanitos",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Estándar",
        isDefault: true,
        calories: 510,
        protein: 7,
        carbs: 61,
        fat: 26,
        fiber: 1,
      },
    ],
    conversions: [{ unitName: "bolsita (25g)", gramsPerUnit: 25 }],
  },
  {
    name: "Cortezas de cerdo",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Fritas",
        isDefault: true,
        calories: 544,
        protein: 55,
        carbs: 0,
        fat: 35,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "bolsa (50g)", gramsPerUnit: 50 }],
  },
  // ── PANES ESPECIALES ─────────────────────────────────────────────────────
  {
    name: "Pan de pita",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Normal",
        isDefault: true,
        calories: 275,
        protein: 9,
        carbs: 55,
        fat: 2.5,
        fiber: 2,
      },
      {
        name: "Integral",
        isDefault: false,
        calories: 262,
        protein: 10,
        carbs: 53,
        fat: 2,
        fiber: 5,
      },
    ],
    conversions: [{ unitName: "unidad", gramsPerUnit: 60 }],
  },
  {
    name: "Pan naan",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Pan naan",
        isDefault: true,
        calories: 317,
        protein: 9,
        carbs: 56,
        fat: 7,
        fiber: 2,
      },
    ],
    conversions: [{ unitName: "unidad", gramsPerUnit: 80 }],
  },
  {
    name: "Pan de hamburguesa",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Hamburguesa",
        isDefault: true,
        calories: 284,
        protein: 9,
        carbs: 52,
        fat: 4.5,
        fiber: 2.5,
      },
    ],
    conversions: [{ unitName: "unidad", gramsPerUnit: 55 }],
  },
  {
    name: "Pan de hot dog",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Hot dog",
        isDefault: true,
        calories: 279,
        protein: 9,
        carbs: 52,
        fat: 3.5,
        fiber: 2,
      },
    ],
    conversions: [{ unitName: "unidad", gramsPerUnit: 45 }],
  },
  {
    name: "Pan chapata",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Pan chapata",
        isDefault: true,
        calories: 269,
        protein: 9,
        carbs: 54,
        fat: 2,
        fiber: 2.5,
      },
    ],
    conversions: [{ unitName: "kg", gramsPerUnit: 1000 }],
  },
  {
    name: "Pan de centeno",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Rebanada",
        isDefault: true,
        calories: 259,
        protein: 8.5,
        carbs: 48,
        fat: 3.3,
        fiber: 6.2,
      },
    ],
    conversions: [
      { unitName: "rebanada", gramsPerUnit: 30 },
      { unitName: "kg", gramsPerUnit: 1000 },
    ],
  },
  {
    name: "Tortilla de trigo (wrap)",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Trigo (wrap)",
        isDefault: true,
        calories: 307,
        protein: 8,
        carbs: 55,
        fat: 6.5,
        fiber: 2,
      },
      {
        name: "Integral",
        isDefault: false,
        calories: 290,
        protein: 9,
        carbs: 52,
        fat: 6,
        fiber: 5,
      },
    ],
    conversions: [{ unitName: "tortilla (25cm)", gramsPerUnit: 45 }],
  },
  {
    name: "Tortilla de maíz",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Tortilla de maíz",
        isDefault: true,
        calories: 355,
        protein: 6,
        carbs: 75,
        fat: 4,
        fiber: 5,
      },
    ],
    conversions: [{ unitName: "tortilla (15cm)", gramsPerUnit: 30 }],
  },
  {
    name: "Biscotes",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Biscotes",
        isDefault: true,
        calories: 415,
        protein: 11,
        carbs: 76,
        fat: 6,
        fiber: 4.5,
      },
    ],
    conversions: [{ unitName: "rebanada", gramsPerUnit: 8 }],
  },
  {
    name: "Tostadas tipo Wasa",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Tostadas tipo Wasa",
        isDefault: true,
        calories: 348,
        protein: 13,
        carbs: 68,
        fat: 2,
        fiber: 17,
      },
    ],
    conversions: [{ unitName: "tostada", gramsPerUnit: 11 }],
  },
  // ── PIZZAS ───────────────────────────────────────────────────────────────
  {
    name: "Pizza margarita (congelada)",
    unit: "g",
    defaultLocation: "congelador",
    variants: [
      {
        name: "Congelada",
        isDefault: true,
        calories: 232,
        protein: 10,
        carbs: 29,
        fat: 8.5,
        fiber: 1.8,
      },
      {
        name: "Horneada",
        isDefault: false,
        calories: 248,
        protein: 11,
        carbs: 28,
        fat: 10,
        fiber: 1.5,
        weightFactor: 0.97,
      },
    ],
    conversions: [
      { unitName: "pizza entera (400g)", gramsPerUnit: 400 },
      { unitName: "ración (1/4)", gramsPerUnit: 100 },
    ],
  },
  {
    name: "Pizza 4 quesos (congelada)",
    unit: "g",
    defaultLocation: "congelador",
    variants: [
      {
        name: "Congelada (4 quesos)",
        isDefault: true,
        calories: 248,
        protein: 12,
        carbs: 28,
        fat: 10,
        fiber: 1.5,
      },
    ],
    conversions: [
      { unitName: "pizza entera (400g)", gramsPerUnit: 400 },
      { unitName: "ración (1/4)", gramsPerUnit: 100 },
    ],
  },
  {
    name: "Pizza barbacoa (congelada)",
    unit: "g",
    defaultLocation: "congelador",
    variants: [
      {
        name: "Congelada (barbacoa)",
        isDefault: true,
        calories: 240,
        protein: 11,
        carbs: 30,
        fat: 9,
        fiber: 1.8,
      },
    ],
    conversions: [
      { unitName: "pizza entera (400g)", gramsPerUnit: 400 },
      { unitName: "ración (1/4)", gramsPerUnit: 100 },
    ],
  },
  {
    name: "Pizza vegetal (congelada)",
    unit: "g",
    defaultLocation: "congelador",
    variants: [
      {
        name: "Congelada (vegetal)",
        isDefault: true,
        calories: 200,
        protein: 8,
        carbs: 27,
        fat: 7,
        fiber: 2.5,
      },
    ],
    conversions: [
      { unitName: "pizza entera (400g)", gramsPerUnit: 400 },
      { unitName: "ración (1/4)", gramsPerUnit: 100 },
    ],
  },
  {
    name: "Base de pizza",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Base precocida",
        isDefault: true,
        calories: 285,
        protein: 9.5,
        carbs: 56,
        fat: 2.5,
        fiber: 2,
      },
    ],
    conversions: [{ unitName: "base (280g)", gramsPerUnit: 280 }],
  },
  {
    name: "Masa de pizza fresca",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Masa fresca",
        isDefault: true,
        calories: 278,
        protein: 8,
        carbs: 55,
        fat: 3.5,
        fiber: 2,
      },
    ],
    conversions: [{ unitName: "bola (250g)", gramsPerUnit: 250 }],
  },
  // ── PLATOS PREPARADOS / CONGELADOS ───────────────────────────────────────
  {
    name: "Paella congelada",
    unit: "g",
    defaultLocation: "congelador",
    variants: [
      {
        name: "Congelada",
        isDefault: true,
        calories: 145,
        protein: 7,
        carbs: 21,
        fat: 3.5,
        fiber: 0.8,
      },
    ],
    conversions: [{ unitName: "ración (280g)", gramsPerUnit: 280 }],
  },
  {
    name: "Arroz tres delicias (preparado)",
    unit: "g",
    defaultLocation: "congelador",
    variants: [
      {
        name: "Preparado",
        isDefault: true,
        calories: 132,
        protein: 6,
        carbs: 22,
        fat: 2.5,
        fiber: 1,
      },
    ],
    conversions: [{ unitName: "ración (250g)", gramsPerUnit: 250 }],
  },
  {
    name: "Lasaña boloñesa (preparada)",
    unit: "g",
    defaultLocation: "congelador",
    variants: [
      {
        name: "Congelada (boloñesa)",
        isDefault: true,
        calories: 126,
        protein: 8,
        carbs: 11,
        fat: 5,
        fiber: 1,
      },
    ],
    conversions: [{ unitName: "ración (400g)", gramsPerUnit: 400 }],
  },
  {
    name: "Canelones de carne (preparados)",
    unit: "g",
    defaultLocation: "congelador",
    variants: [
      {
        name: "Congelados",
        isDefault: true,
        calories: 149,
        protein: 9,
        carbs: 13,
        fat: 6,
        fiber: 1,
      },
    ],
    conversions: [{ unitName: "bandeja (375g)", gramsPerUnit: 375 }],
  },
  {
    name: "Croquetas (congeladas)",
    unit: "g",
    defaultLocation: "congelador",
    variants: [
      {
        name: "Congeladas",
        isDefault: true,
        calories: 218,
        protein: 8,
        carbs: 20,
        fat: 11,
        fiber: 1.2,
      },
      {
        name: "Fritas",
        isDefault: false,
        calories: 272,
        protein: 9,
        carbs: 22,
        fat: 16,
        fiber: 1,
        weightFactor: 0.95,
      },
    ],
    conversions: [
      { unitName: "unidad (18g)", gramsPerUnit: 18 },
      { unitName: "ración (6 ud)", gramsPerUnit: 108 },
    ],
  },
  {
    name: "Empanadillas (congeladas)",
    unit: "g",
    defaultLocation: "congelador",
    variants: [
      {
        name: "Congeladas",
        isDefault: true,
        calories: 195,
        protein: 8,
        carbs: 22,
        fat: 8,
        fiber: 1.5,
      },
      {
        name: "Horneadas",
        isDefault: false,
        calories: 208,
        protein: 8,
        carbs: 22,
        fat: 10,
        fiber: 1.5,
        weightFactor: 0.97,
      },
    ],
    conversions: [{ unitName: "unidad (25g)", gramsPerUnit: 25 }],
  },
  {
    name: "Nuggets de pollo",
    unit: "g",
    defaultLocation: "congelador",
    variants: [
      {
        name: "Congelados",
        isDefault: true,
        calories: 216,
        protein: 13,
        carbs: 12,
        fat: 12,
        fiber: 1,
      },
      {
        name: "Fritos/horneados",
        isDefault: false,
        calories: 245,
        protein: 14,
        carbs: 12,
        fat: 14,
        fiber: 1,
        weightFactor: 0.95,
      },
    ],
    conversions: [
      { unitName: "pieza (18g)", gramsPerUnit: 18 },
      { unitName: "ración (6 ud)", gramsPerUnit: 108 },
    ],
  },
  {
    name: "Fingers de pollo",
    unit: "g",
    defaultLocation: "congelador",
    variants: [
      {
        name: "Congelados",
        isDefault: true,
        calories: 206,
        protein: 13,
        carbs: 14,
        fat: 10,
        fiber: 1.2,
      },
    ],
    conversions: [{ unitName: "pieza (30g)", gramsPerUnit: 30 }],
  },
  {
    name: "Delicias de pollo",
    unit: "g",
    defaultLocation: "congelador",
    variants: [
      {
        name: "Congeladas",
        isDefault: true,
        calories: 162,
        protein: 15,
        carbs: 10,
        fat: 7,
        fiber: 0.5,
      },
      {
        name: "Horneadas/fritas",
        isDefault: false,
        calories: 188,
        protein: 18,
        carbs: 10,
        fat: 10,
        fiber: 0.5,
        weightFactor: 0.93,
      },
    ],
    conversions: [
      { unitName: "pieza (35g)", gramsPerUnit: 35 },
      { unitName: "caja (300g)", gramsPerUnit: 300 },
    ],
  },
  {
    name: "Varitas de merluza (congeladas)",
    unit: "g",
    defaultLocation: "congelador",
    variants: [
      {
        name: "Congeladas",
        isDefault: true,
        calories: 160,
        protein: 10,
        carbs: 13,
        fat: 7,
        fiber: 0.8,
      },
    ],
    conversions: [{ unitName: "varita (35g)", gramsPerUnit: 35 }],
  },
  {
    name: "Palitos de surimi",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Palitos de surimi",
        isDefault: true,
        calories: 95,
        protein: 9,
        carbs: 12,
        fat: 1.5,
        fiber: 0.5,
      },
    ],
    conversions: [{ unitName: "palito (25g)", gramsPerUnit: 25 }],
  },
  {
    name: "Ensaladilla rusa (preparada)",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Preparada",
        isDefault: true,
        calories: 110,
        protein: 2,
        carbs: 10,
        fat: 7,
        fiber: 1.2,
      },
    ],
    conversions: [{ unitName: "ración (200g)", gramsPerUnit: 200 }],
  },
  {
    name: "Gazpacho (brick)",
    unit: "ml",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Gazpacho",
        isDefault: true,
        calories: 25,
        protein: 0.8,
        carbs: 4.5,
        fat: 0.5,
        fiber: 0.9,
      },
    ],
    conversions: [
      { unitName: "brick (330ml)", gramsPerUnit: 330 },
      { unitName: "vaso (250ml)", gramsPerUnit: 250 },
    ],
  },
  {
    name: "Salmorejo (brick)",
    unit: "ml",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Salmorejo",
        isDefault: true,
        calories: 71,
        protein: 1.5,
        carbs: 10,
        fat: 2.8,
        fiber: 1.2,
      },
    ],
    conversions: [
      { unitName: "brick (330ml)", gramsPerUnit: 330 },
      { unitName: "ración (150ml)", gramsPerUnit: 150 },
    ],
  },
  {
    name: "Fabada asturiana (conserva)",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Conserva (lata)",
        isDefault: true,
        calories: 112,
        protein: 7,
        carbs: 10,
        fat: 4.5,
        fiber: 5,
      },
    ],
    conversions: [{ unitName: "lata (425g)", gramsPerUnit: 425 }],
  },
  {
    name: "Lentejas guisadas (conserva)",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Conserva (lata)",
        isDefault: true,
        calories: 97,
        protein: 6,
        carbs: 14,
        fat: 2.5,
        fiber: 5,
      },
    ],
    conversions: [{ unitName: "lata (425g)", gramsPerUnit: 425 }],
  },
  {
    name: "Cocido madrileño (conserva)",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Conserva (lata)",
        isDefault: true,
        calories: 126,
        protein: 8,
        carbs: 10,
        fat: 5.5,
        fiber: 3.5,
      },
    ],
    conversions: [{ unitName: "lata (425g)", gramsPerUnit: 425 }],
  },
  // ── CONSERVAS Y ENCURTIDOS ───────────────────────────────────────────────
  {
    name: "Pepinillos en vinagre",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "En vinagre",
        isDefault: true,
        calories: 11,
        protein: 0.7,
        carbs: 1.8,
        fat: 0.1,
        fiber: 0.9,
      },
    ],
    conversions: [
      { unitName: "pepinillo pequeño (10g)", gramsPerUnit: 10 },
      { unitName: "frasco (360g)", gramsPerUnit: 360 },
    ],
  },
  {
    name: "Aceitunas verdes (sin hueso)",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Verdes (manzanilla)",
        isDefault: true,
        calories: 145,
        protein: 1,
        carbs: 3.8,
        fat: 15,
        fiber: 3.3,
      },
    ],
    conversions: [
      { unitName: "aceituna (5g)", gramsPerUnit: 5 },
      { unitName: "lata (185g escurrida)", gramsPerUnit: 185 },
    ],
  },
  {
    name: "Aceitunas negras (sin hueso)",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Negras",
        isDefault: true,
        calories: 151,
        protein: 1,
        carbs: 4,
        fat: 16,
        fiber: 3.2,
      },
    ],
    conversions: [{ unitName: "aceituna (5g)", gramsPerUnit: 5 }],
  },
  {
    name: "Aceitunas rellenas (anchoa)",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Rellenas de anchoa",
        isDefault: true,
        calories: 145,
        protein: 1.5,
        carbs: 3.5,
        fat: 15,
        fiber: 3,
      },
    ],
    conversions: [{ unitName: "aceituna (7g)", gramsPerUnit: 7 }],
  },
  {
    name: "Cebolletas en vinagre",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "En vinagre",
        isDefault: true,
        calories: 24,
        protein: 0.8,
        carbs: 5,
        fat: 0.1,
        fiber: 1,
      },
    ],
    conversions: [{ unitName: "frasco (180g)", gramsPerUnit: 180 }],
  },
  {
    name: "Pimientos del piquillo (conserva)",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Del piquillo (lata)",
        isDefault: true,
        calories: 39,
        protein: 1,
        carbs: 7.5,
        fat: 0.4,
        fiber: 2,
      },
    ],
    conversions: [
      { unitName: "pimiento (30g)", gramsPerUnit: 30 },
      { unitName: "lata (390g)", gramsPerUnit: 390 },
    ],
  },
  {
    name: "Espárragos blancos (conserva)",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Blancos (lata)",
        isDefault: true,
        calories: 18,
        protein: 2,
        carbs: 2.5,
        fat: 0.2,
        fiber: 1.5,
      },
    ],
    conversions: [
      { unitName: "espárrago (15g)", gramsPerUnit: 15 },
      { unitName: "lata (430g)", gramsPerUnit: 430 },
    ],
  },
  {
    name: "Maíz dulce en lata",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "En lata (escurrido)",
        isDefault: true,
        calories: 86,
        protein: 3.2,
        carbs: 18.7,
        fat: 1.2,
        fiber: 2,
      },
    ],
    conversions: [
      { unitName: "lata pequeña (75g escurrida)", gramsPerUnit: 75 },
      { unitName: "lata (215g escurrida)", gramsPerUnit: 215 },
    ],
  },
  {
    name: "Bonito del norte en aceite",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "En aceite (escurrido)",
        isDefault: true,
        calories: 160,
        protein: 27,
        carbs: 0,
        fat: 5.5,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "lata (112g escurrida)", gramsPerUnit: 112 }],
  },
  {
    name: "Melva en aceite",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "En aceite (escurrida)",
        isDefault: true,
        calories: 197,
        protein: 20,
        carbs: 0,
        fat: 13,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "lata (90g)", gramsPerUnit: 90 }],
  },
  {
    name: "Sardinillas en aceite",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "En aceite",
        isDefault: true,
        calories: 208,
        protein: 22,
        carbs: 0,
        fat: 13,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "lata (85g)", gramsPerUnit: 85 }],
  },
  {
    name: "Mejillones en escabeche (lata)",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "En escabeche",
        isDefault: true,
        calories: 168,
        protein: 16.9,
        carbs: 3.8,
        fat: 9.5,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "lata (80g escurrida)", gramsPerUnit: 80 }],
  },
  {
    name: "Berberechos en lata",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Al natural (escurridos)",
        isDefault: true,
        calories: 58,
        protein: 11.5,
        carbs: 0,
        fat: 1,
        fiber: 0,
      },
      {
        name: "En aceite",
        isDefault: false,
        calories: 130,
        protein: 12,
        carbs: 0,
        fat: 9,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "lata (63g escurrida)", gramsPerUnit: 63 }],
  },
  {
    name: "Navajas en lata",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "En aceite",
        isDefault: true,
        calories: 165,
        protein: 16,
        carbs: 0,
        fat: 11,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "lata (63g)", gramsPerUnit: 63 }],
  },
  // ── BEBIDAS CON MARCA ─────────────────────────────────────────────────────
  {
    name: "Coca-Cola",
    unit: "ml",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Clásica",
        isDefault: true,
        calories: 42,
        protein: 0,
        carbs: 10.6,
        fat: 0,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "lata (330ml)", gramsPerUnit: 330 },
      { unitName: "botella (500ml)", gramsPerUnit: 500 },
    ],
  },
  {
    name: "Coca-Cola Zero",
    unit: "ml",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Zero Sugar",
        isDefault: true,
        calories: 1,
        protein: 0,
        carbs: 0.1,
        fat: 0,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "lata (330ml)", gramsPerUnit: 330 },
      { unitName: "botella (500ml)", gramsPerUnit: 500 },
    ],
  },
  {
    name: "Fanta Naranja",
    unit: "ml",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Naranja",
        isDefault: true,
        calories: 44,
        protein: 0,
        carbs: 11,
        fat: 0,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "lata (330ml)", gramsPerUnit: 330 },
      { unitName: "botella (500ml)", gramsPerUnit: 500 },
    ],
  },
  {
    name: "Fanta Naranja Zero",
    unit: "ml",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Zero azúcar",
        isDefault: true,
        calories: 3,
        protein: 0,
        carbs: 0.7,
        fat: 0,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "lata (330ml)", gramsPerUnit: 330 }],
  },
  {
    name: "Fanta Limón",
    unit: "ml",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Limón",
        isDefault: true,
        calories: 43,
        protein: 0,
        carbs: 10.7,
        fat: 0,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "lata (330ml)", gramsPerUnit: 330 },
      { unitName: "botella (500ml)", gramsPerUnit: 500 },
    ],
  },
  {
    name: "7UP",
    unit: "ml",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Limón/lima",
        isDefault: true,
        calories: 42,
        protein: 0,
        carbs: 10.6,
        fat: 0,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "lata (330ml)", gramsPerUnit: 330 }],
  },
  {
    name: "7UP Free",
    unit: "ml",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Sin azúcar",
        isDefault: true,
        calories: 1,
        protein: 0,
        carbs: 0.1,
        fat: 0,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "lata (330ml)", gramsPerUnit: 330 }],
  },
  {
    name: "Monster Energy",
    unit: "ml",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Original (verde)",
        isDefault: true,
        calories: 46,
        protein: 0,
        carbs: 11.3,
        fat: 0,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "lata (500ml)", gramsPerUnit: 500 }],
  },
  {
    name: "Monster Zero Ultra",
    unit: "ml",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Ultra (sin azúcar)",
        isDefault: true,
        calories: 8,
        protein: 0.5,
        carbs: 1.7,
        fat: 0,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "lata (500ml)", gramsPerUnit: 500 }],
  },
  {
    name: "Aquarius Naranja",
    unit: "ml",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Naranja",
        isDefault: true,
        calories: 23,
        protein: 0,
        carbs: 5.6,
        fat: 0,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "botella (500ml)", gramsPerUnit: 500 }],
  },
  {
    name: "Nestea Limón",
    unit: "ml",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Limón (botella)",
        isDefault: true,
        calories: 18,
        protein: 0,
        carbs: 4.4,
        fat: 0,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "botella (500ml)", gramsPerUnit: 500 }],
  },
  {
    name: "Nestea Zero",
    unit: "ml",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Zero",
        isDefault: true,
        calories: 2,
        protein: 0,
        carbs: 0.4,
        fat: 0,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "botella (500ml)", gramsPerUnit: 500 }],
  },
  {
    name: "Appletiser",
    unit: "ml",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Manzana con gas",
        isDefault: true,
        calories: 46,
        protein: 0.3,
        carbs: 11,
        fat: 0,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "botella (330ml)", gramsPerUnit: 330 }],
  },
  // ── UNTABLES Y SALSAS EXTRA ──────────────────────────────────────────────
  {
    name: "Nocilla",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Clásica (doble sabor)",
        isDefault: true,
        calories: 531,
        protein: 6.5,
        carbs: 54,
        fat: 32,
        fiber: 3.2,
      },
      {
        name: "Sabor chocolate",
        isDefault: false,
        calories: 538,
        protein: 6,
        carbs: 55,
        fat: 33,
        fiber: 3,
      },
    ],
    conversions: [{ unitName: "cucharada (20g)", gramsPerUnit: 20 }],
  },
  {
    name: "Nutella",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Original",
        isDefault: true,
        calories: 539,
        protein: 6.3,
        carbs: 57.5,
        fat: 30.9,
        fiber: 3.4,
      },
    ],
    conversions: [{ unitName: "cucharada (20g)", gramsPerUnit: 20 }],
  },
  {
    name: "Hummus",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Hummus clásico",
        isDefault: true,
        calories: 177,
        protein: 8,
        carbs: 14,
        fat: 10,
        fiber: 6,
      },
    ],
    conversions: [
      { unitName: "cucharada (15g)", gramsPerUnit: 15 },
      { unitName: "tarrina (200g)", gramsPerUnit: 200 },
    ],
  },
  {
    name: "Guacamole",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Guacamole",
        isDefault: true,
        calories: 160,
        protein: 2,
        carbs: 9,
        fat: 15,
        fiber: 6.7,
      },
    ],
    conversions: [
      { unitName: "cucharada (15g)", gramsPerUnit: 15 },
      { unitName: "tarrina (200g)", gramsPerUnit: 200 },
    ],
  },
  {
    name: "Tzatziki",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Tzatziki",
        isDefault: true,
        calories: 75,
        protein: 4,
        carbs: 4,
        fat: 5.5,
        fiber: 0.3,
      },
    ],
    conversions: [{ unitName: "cucharada (15g)", gramsPerUnit: 15 }],
  },
  {
    name: "Salsa brava",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Salsa brava",
        isDefault: true,
        calories: 55,
        protein: 1,
        carbs: 10,
        fat: 2,
        fiber: 1.2,
      },
    ],
    conversions: [{ unitName: "cucharada (15g)", gramsPerUnit: 15 }],
  },
  {
    name: "Salsa alioli",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Alioli casero",
        isDefault: true,
        calories: 350,
        protein: 1.5,
        carbs: 4,
        fat: 38,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "cucharada (15g)", gramsPerUnit: 15 }],
  },
  {
    name: "Mermelada de fresa",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Mermelada",
        isDefault: true,
        calories: 250,
        protein: 0.5,
        carbs: 62,
        fat: 0.1,
        fiber: 1,
      },
      {
        name: "Sin azúcar añadido",
        isDefault: false,
        calories: 120,
        protein: 0.5,
        carbs: 30,
        fat: 0.1,
        fiber: 1,
      },
    ],
    conversions: [{ unitName: "cucharada (20g)", gramsPerUnit: 20 }],
  },
  {
    name: "Mermelada de melocotón",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Mermelada",
        isDefault: true,
        calories: 252,
        protein: 0.4,
        carbs: 62,
        fat: 0.1,
        fiber: 0.8,
      },
    ],
    conversions: [{ unitName: "cucharada (20g)", gramsPerUnit: 20 }],
  },
  {
    name: "Mermelada de naranja",
    unit: "g",
    defaultLocation: "nevera",
    variants: [
      {
        name: "Mermelada",
        isDefault: true,
        calories: 241,
        protein: 0.5,
        carbs: 60,
        fat: 0.1,
        fiber: 0.5,
      },
    ],
    conversions: [{ unitName: "cucharada (20g)", gramsPerUnit: 20 }],
  },
  {
    name: "Crema de cacahuete",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Natural (sin azúcar)",
        isDefault: true,
        calories: 597,
        protein: 25,
        carbs: 22,
        fat: 51,
        fiber: 6,
      },
      {
        name: "Con azúcar",
        isDefault: false,
        calories: 620,
        protein: 24,
        carbs: 27,
        fat: 50,
        fiber: 5,
      },
    ],
    conversions: [
      { unitName: "cucharada (16g)", gramsPerUnit: 16 },
      { unitName: "cucharadita (8g)", gramsPerUnit: 8 },
    ],
  },
  // ── ÍTEMS ADICIONALES DEL SQL07 ──────────────────────────────────────────
  {
    name: "Nachos (genérico)",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Con sal",
        isDefault: true,
        calories: 477,
        protein: 7,
        carbs: 60,
        fat: 24,
        fiber: 4,
      },
      {
        name: "Con queso",
        isDefault: false,
        calories: 490,
        protein: 7,
        carbs: 58,
        fat: 26,
        fiber: 4,
      },
    ],
    conversions: [{ unitName: "ración (30g)", gramsPerUnit: 30 }],
  },
  {
    name: "Fritos de maíz",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Fritos de maíz",
        isDefault: true,
        calories: 502,
        protein: 8,
        carbs: 67,
        fat: 22,
        fiber: 4,
      },
    ],
    conversions: [{ unitName: "bolsita (30g)", gramsPerUnit: 30 }],
  },
  {
    name: "Galletas saladas",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Galletas saladas",
        isDefault: true,
        calories: 460,
        protein: 9,
        carbs: 68,
        fat: 17,
        fiber: 2.5,
      },
    ],
    conversions: [{ unitName: "galleta (6g)", gramsPerUnit: 6 }],
  },
  {
    name: "Regañás",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Clásicas",
        isDefault: true,
        calories: 450,
        protein: 10,
        carbs: 68,
        fat: 16,
        fiber: 3,
      },
    ],
    conversions: [{ unitName: "bolsa (160g)", gramsPerUnit: 160 }],
  },
  {
    name: "Picos de pan",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Picos de pan",
        isDefault: true,
        calories: 390,
        protein: 10,
        carbs: 72,
        fat: 6,
        fiber: 3,
      },
    ],
    conversions: [{ unitName: "pico (4g)", gramsPerUnit: 4 }],
  },
  {
    name: "Crackers integrales",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Integrales",
        isDefault: true,
        calories: 410,
        protein: 12,
        carbs: 65,
        fat: 11,
        fiber: 8,
      },
    ],
    conversions: [{ unitName: "cracker (8g)", gramsPerUnit: 8 }],
  },
  {
    name: "Pan de avena",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Pan de avena",
        isDefault: true,
        calories: 270,
        protein: 9.5,
        carbs: 48,
        fat: 4,
        fiber: 4,
      },
    ],
    conversions: [{ unitName: "rebanada", gramsPerUnit: 30 }],
  },
  {
    name: "Guisantes en lata",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "En lata (escurridos)",
        isDefault: true,
        calories: 70,
        protein: 5,
        carbs: 12,
        fat: 0.4,
        fiber: 4.5,
      },
    ],
    conversions: [{ unitName: "lata (215g escurrida)", gramsPerUnit: 215 }],
  },
  {
    name: "Caballa en aceite",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "En aceite (escurrida)",
        isDefault: true,
        calories: 180,
        protein: 21,
        carbs: 0,
        fat: 11,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "lata (120g)", gramsPerUnit: 120 }],
  },
  {
    name: "Agua con gas",
    unit: "ml",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Con gas",
        isDefault: true,
        calories: 0,
        protein: 0,
        carbs: 0,
        fat: 0,
        fiber: 0,
      },
    ],
    conversions: [
      { unitName: "botella (500ml)", gramsPerUnit: 500 },
      { unitName: "vaso (250ml)", gramsPerUnit: 250 },
    ],
  },
  {
    name: "Zumo de piña (brick)",
    unit: "ml",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Zumo de piña (100%)",
        isDefault: true,
        calories: 50,
        protein: 0.4,
        carbs: 12.3,
        fat: 0.1,
        fiber: 0.2,
      },
    ],
    conversions: [
      { unitName: "brick (200ml)", gramsPerUnit: 200 },
      { unitName: "vaso (250ml)", gramsPerUnit: 250 },
    ],
  },
  {
    name: "Néctar de melocotón",
    unit: "ml",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Néctar de melocotón",
        isDefault: true,
        calories: 52,
        protein: 0.4,
        carbs: 12.5,
        fat: 0.1,
        fiber: 0.3,
      },
    ],
    conversions: [{ unitName: "brick (200ml)", gramsPerUnit: 200 }],
  },
  {
    name: "Tónica",
    unit: "ml",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Tónica",
        isDefault: true,
        calories: 34,
        protein: 0,
        carbs: 8,
        fat: 0,
        fiber: 0,
      },
      {
        name: "Sin azúcar",
        isDefault: false,
        calories: 2,
        protein: 0,
        carbs: 0.3,
        fat: 0,
        fiber: 0,
      },
    ],
    conversions: [{ unitName: "lata (250ml)", gramsPerUnit: 250 }],
  },
  {
    name: "Salsa barbacoa",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Barbacoa",
        isDefault: true,
        calories: 190,
        protein: 1.5,
        carbs: 38,
        fat: 2.5,
        fiber: 0.5,
      },
    ],
    conversions: [{ unitName: "cucharada (15g)", gramsPerUnit: 15 }],
  },
  {
    name: "Salsa para pizza (tomate)",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Tomate para pizza",
        isDefault: true,
        calories: 55,
        protein: 2,
        carbs: 10,
        fat: 1,
        fiber: 1.5,
      },
    ],
    conversions: [{ unitName: "cucharada (15g)", gramsPerUnit: 15 }],
  },
  {
    name: "Tahini",
    unit: "g",
    defaultLocation: "despensa",
    variants: [
      {
        name: "Sésamo tostado",
        isDefault: true,
        calories: 595,
        protein: 17,
        carbs: 21,
        fat: 54,
        fiber: 9,
      },
    ],
    conversions: [{ unitName: "cucharada (15g)", gramsPerUnit: 15 }],
  },
];
